Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebQuiz.Models;
using WebQuiz.Models.RepositoryIntefraces;
using WebQuiz.Models.Service;
using static WebQuiz.Models.QuizState;

namespace WebQuiz.Controllers
{
    [Serializable]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IResultRepository resultRepository;
        private readonly IService service;
        public HomeController(ILogger<HomeController> logger, IResultRepository resultRepository, IService service)
        {
            _logger = logger;
            this.resultRepository = resultRepository;
            this.service = service;
        }

        // загрузка главной страницы
        [HttpGet]
        public async Task<IActionResult> Index(bool authorized = true)
        {
            if (!authorized)
            {
                ViewBag.ErrorMessage = "Выполните вход в аккаунт!";
            }
            try
            {
                return View(await resultRepository.GetTop10ResultsAsync());
            }
            catch(Exception ex)
            {
                var response = "[GET] Exception in: Controller: " + nameof(HomeController) + "; Action: " + nameof(Index) + ";\n" + ex;
                _logger.LogError(response);

                return View(new List<Result>());
            }

        }

        // клик на кнопку "флаги", начало викторины
        public IActionResult Flags()
        {
            if (CurrentUser._CurrentUser != null)     // пользователь авторизован
            {
                QuizState.Type = QuizType.Flags;                            // тип викторины
                return RedirectToAction("Index", "Quiz", new { type = 1 }); // направляем на страницу с вопросом, тип 1 - исп. сущность "страна"
            }
            else                                                                // пользователь не авторизован
            {
                return RedirectToAction("Index", new {authorized = false});     // перенаправляем на эту же страницу, появляется ошибка
            }
            
        }

        // клик на кнопку "границы", то же самое, что и в Flags()
        public IActionResult Borders()
        {
            if (CurrentUser._CurrentUser != null)
            {
                QuizState.Type = QuizType.Borders;
                return RedirectToAction("Index", "Quiz", new { type = 1 });
            }
            else
            {
                return RedirectToAction("Index", new { authorized = false });
            }
        }

        // клик на кнопку "правители", то же самое, кроме типа. Тип 2 - сущность "правитель"
        public IActionResult Rulers()
        {
            if (CurrentUser._CurrentUser != null)
            {
                QuizState.Type = QuizType.Rulers;
                return RedirectToAction("Index", "Quiz", new { type = 2 });
            }
            else
            {
                return RedirectToAction("Index", new { authorized = false });
            }
        }

        // переход на представление с инфо о приложении/вар-ами связи
        [HttpGet]
        public IActionResult InfoNContact()
        {
            return View();
        }

        // переход на представление Statistics(все ответы пользователей)
        [HttpGet]
        public async Task<IActionResult> Statistics() 
        {
            return View(await service.LoadStatisticsAsync());
        }

        // пользователь использует сортировку или поиск
        [HttpPost]
        public async Task<IActionResult> Statistics(string searchString, string firstSortParameter, string secondSortParameter)
        {
            return View(await service.LoadStatisticsAsync(searchString, firstSortParameter, secondSortParameter));
        }
        // переход на страницу с рейтингом игроков
        [HttpGet]
        public IActionResult Players()
        {
            return View(service.FormUserRating());
        }
        //выполняется поиск и сортировка
        [HttpPost]
        public IActionResult Players(string searchString, string sortParameter)
        {
            return View(service.FormUserRating(searchString, sortParameter));
        }
        //переход на страницу со статистикой стран
        [HttpGet]
        public async Task<IActionResult> CountriesStats()
        {
            return View(await service.CountriesStatsAsync());
        }
        //используется сортировка и поиск
        [HttpPost]
        public async Task<IActionResult> CountriesStats(string searchString, string sortParameter)
        {
            return View(await service.CountriesStatsAsync(searchString, sortParameter));
        }
        // переход на страницу со статистикой правителей
        [HttpGet]
        public async Task<IActionResult> RulersStats()
        {
            return View(await service.RulersStatsAsync());
        }
        //используется поиск и сортировка
        [HttpPost]
        public async Task<IActionResult> RulersStats(string searchString, string sortParameter)
        {
            return View(await service.RulersStatsAsync(searchString, sortParameter));
        }
    }
}

Controllers/OffersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebQuiz.Models;
using WebQuiz.Models.RepositoryIntefraces;
using WebQuiz.Models.Service;

namespace WebQuiz.Controllers
{
    public class OffersController : Controller
    {
        private readonly IOfferRepository repository;
        private readonly IService service;

        public OffersController(IOfferRepository repository, IService service)
        {
            this.repository = repository;
            this.service = service;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Offer> offers = repository.GetAll().ToListAsync().Result.OrderByDescending(x => DateTime.Parse(x.CreatedDate)).ToList();

                ViewBag.UserRoles = await service.GetRolesOfUsersAsync(offers); // модераторы могут удалять комментарии
                return View(offers);
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(string offerField)
        {
            await service.PostOfferAsync(offerField);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteOffer(int offerId)
        {
            await repository.DeleteAsync(offerId);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/CountriesStats.cshtml
@model List<Country>

<div class="sidenav">
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Инфо/Связь" asp-action="InfoNContact" asp-controller="Home" />
    </form>
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Предложения" asp-controller="Offers" asp-action="Index" />
    </form>
</div>

<center>

    @{
        <h1>Узнаваемость стран:</h1> <br /> <br />

        <form method="post">
            <div style="font-size:18pt">

                <input type="text" style="border-radius:5px;width:642px;font-weight:bold" placeholder="Поиск" name="searchString" />
                <input type="submit" style="background-color:green;color:white;border-radius:5px;width:214px;font-weight:bold" value="Найти" /> <br />

                <select class="sortselect" name="sortParameter" style="margin:20px 0 20px 0">
                    <option value="name">Название</option>
                    <option value="displayed">Количество показов</option>
                    <option value="guessed">Верно угадано</option>
                    <option value="percent">Верно угадано, %</option>
                </select>
            </div>
        </form>
        <br />

        <table>
            <thead>
                <tr>
                    <th>Страна(регион):</th>
                    <th>Показана, раз</th>
                    <th>Угадана, раз</th>
                    <th>Угадана, %</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var country in Model)
                    {
                        <tr>
                            <td>@(char.ToUpper(country.RightAnswers.Split("/")[0][0]) + country.RightAnswers.Split("/")[0].Substring(1))</td>
                            <td>@country.TimesDisplayed</td>
                            <td>@country.TimesGuessed</td>
                            @if(country.TimesDisplayed == 0)
                            {
                                <td>0</td>
                            }
                            else
                            {
                                double percent = Math.Round((double)((country.TimesGuessed * 100) / country.TimesDisplayed), 2);
                                if(percent >= 0 && percent <= 30)
                                {
                                    <td style="color:red;font-weight:bold">@percent</td>
                                }
                                else if (percent >= 31 && percent <= 70)
                                {
                                    <td style="color:orange;font-weight:bold">@percent</td>
                                }
                                else if (percent >= 71 && percent <= 100)
                                {
                                    <td style="color:green;font-weight:bold">@percent</td>
                                }
                                else { <td>@percent</td> }
                            }
                        </tr>

                    }   
                }
            </tbody>
        </table>
    }

</center>

Views/Home/Index.cshtml
@model List<Result>?



<div style="font-family:'Century Gothic'">

    <div style="">

        <div class="sidenav">
            <form method="get">
                <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Инфо/Связь" asp-action="InfoNContact" asp-controller="Home"/>
            </form>
            <form method="get">
                <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Предложения" asp-controller="Offers" asp-action="Index" />
            </form>
        </div>

        <center>

            <h4 style="font-size:30pt;color:red">@ViewBag.ErrorMessage</h4>

            <img src="https://st.overclockers.ru/images/lab/2017/04/04/1/atlant_big.jpg"
                 style="width:864px;height:486px" />

            <br /> <br /><h1>Выберите тип викторины:</h1> <br /> <br />

            <form method="post">

                <input style="background-color:green;color:white;font-size:22pt;border-radius:5px" class="flags"
                       type="submit" value="Флаги" asp-action="Flags" />

                <input style="background-color:green;color:white;font-size:22pt;border-radius:5px;margin:0 0 0 10px"
                       type="submit" value="Границы" asp-action="Borders" />

                <input style="background-color:green;color:white;font-size:22pt;border-radius:5px;margin:0 0 0 10px" class="rulers"
                       type="submit" value="Правители" asp-action="Rulers" asp-controller="Home" />

            </form>

            <script>
                anime({
                    targets: '.flags',
                    translateX: -80,
                    direction: 'alternate',
                    easing: 'easeInOutSine',
                    duration: 400,
                    delay: 250,
                });
                anime({
                    targets: '.rulers',
                    translateX: 80,
                    direction: 'alternate',
                    easing: 'easeInOutSine',
                    duration: 400,
                    delay: 250,
                });
            </script>

            @{
                <br /> <br /> <br />
                <h2>Топ-10 ответов пользователей:</h2> <br /> <br />

                if(Model.Count < 10) { <h2>Ответов пользователей мало, Вы можете легко попасть в топ!</h2> }
                else
                {
                    <table>
                        <thead>
                            <tr>
                                <th>Пользователь</th>
                                <th>Дано верных ответов</th>
                                <th>Очков</th>
                                <th>Время</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var result in Model)
                                {
                                    <tr>
                                        <td>@result.UserName</td>
                                        <td>@result.CorrectAnswers</td>
                                        <td>@result.Points</td>
                                        <td>@result.Time</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                }
            }
        </center>

    </div>

</div>

Views/Home/InfoNContact.cshtml
<p2 style="font-size:22pt">
    На данном веб-сайте Вы сможете пройти несколько типов викторин: <br />
    <ul>
        <li>На знание флагов стран мира</li>
        <li>На знание границ стран мира</li>
        <li>На знание правителей стран мира</li>
    </ul>
    <br />
    Чтобы начать викторину, необходимо зарегистрироваться и выполнить вход <br />
    Также Вы можете попать в топ пользователей, если количество верных ответов, а также время выполнения будут лучше, чем у других.
</p2>
<br />
<br />

<hr style="width:70%"/>

<br /> <br />

<p2 style="font-size:22pt">
    Вы можете связаться с разработчиком напрямую:
    <ul>
        <li> <a href="https://vk.com/gevrlegend" target="_blank">Вконтакте</a> </li>
        <li> <a href="https://t.me/popoiri" target="_blank">Телеграм</a> </li>
    </ul>
</p2>

Views/Home/Players.cshtml
@model List<UserRating>

<div class="sidenav">
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Инфо/Связь" asp-action="InfoNContact" asp-controller="Home" />
    </form>
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Предложения" asp-controller="Offers" asp-action="Index" />
    </form>
</div>

<center>
    @{
        <h1>Рейтинг пользователей:</h1> <br /> <br />
        <form method="post">
            <div style="font-size:18pt">

                <input type="text" style="border-radius:5px;width:642px;font-weight:bold" placeholder="Поиск" name="searchString" />
                <input type="submit" style="background-color:green;color:white;border-radius:5px;width:214px;font-weight:bold" value="Найти" /> <br />

                <select class="sortselect" name="sortParameter" style="margin:20px 0 20px 0">
                    <option value="position">Позиция в рейтинге</option>
                    <option value="user">Именя пользователя</option>
                    <option value="points">Очков</option>
                    <option value="correctAnswers">Верных ответов</option>
                    <option value="time">Время</option>
                </select>
            </div>
        </form>
        <br />
        <table>
            <thead>
                <tr>
                    <th>Место в рейтинге</th>
                    <th>Всего пройдено викторин</th>
                    <th>Пользователь</th>
                    <th>Всего очков</th>
                    <th>Всего верных ответов</th>
                    <th>Всего секунд</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var user in Model)
                    {
                        <tr>
                            <td>@user.PositionInRating</td>
                            <td>@user.TotalTries</td>
                            <td>@user.UserName</td>
                            <td style="width:250px" class="points">@user.TotalPoints</td>
                            <td>@user.TotalCorrectAnswers</td>
                            <td>@user.TotalSeconds</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        }
</center>

<!--Так и не понял, так сделать плавное возрастание от 0 до значения Points. Если писать что-то такое:
    var endValue = parseFloat(number.textContent), то число будет выдаваться округленным до int.
    В данный момент идет до своего значения, однако криво: 6.25,5.25 в моменте, например.
-->

<script>
    const animNums = document.querySelectorAll('.points');
    animNums.forEach((number) => {
        anime({
            round: 10,
            targets: number,
            textContent: [0, number.textContent],
            easing: 'linear',
            duration: 1000,
        });
    });
</script>

Views/Home/RulersStats.cshtml
@model List<Ruler>

<div class="sidenav">
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Инфо/Связь" asp-action="InfoNContact" asp-controller="Home" />
    </form>
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Предложения" asp-controller="Offers" asp-action="Index" />
    </form>
</div>

<center>

    @{
        <h1>Узнаваемость правителей:</h1> <br /> <br />

        <form method="post">
            <div style="font-size:18pt">

                <input type="text" style="border-radius:5px;width:642px;font-weight:bold" placeholder="Поиск" name="searchString" />
                <input type="submit" style="background-color:green;color:white;border-radius:5px;width:214px;font-weight:bold" value="Найти" /> <br />

                <select class="sortselect" name="sortParameter" style="margin:20px 0 20px 0">
                    <option value="name">Название</option>
                    <option value="displayed">Количество показов</option>
                    <option value="guessed">Верно угадано</option>
                    <option value="percent">Верно угадано, %</option>
                </select>
            </div>
        </form>
        <br />

        <table>
            <thead>
                <tr>
                    <th>Правитель:</th>
                    <th>Показан, раз</th>
                    <th>Угадан, раз</th>
                    <th>Угадан, %</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var ruler in Model)
                    {
                        <tr>
                            <td>@(char.ToUpper(ruler.RightAnswers.Split("/")[0][0]) + ruler.RightAnswers.Split("/")[0].Substring(1))</td>
                            <td>@ruler.TimesDisplayed</td>
                            <td>@ruler.TimesGuessed</td>
                            @if (ruler.TimesDisplayed == 0)
                            {
                                <td>0</td>
                            }
                            else
                            {
                                double percent = Math.Round((double)((ruler.TimesGuessed * 100) / ruler.TimesDisplayed), 2);
                                if (percent >= 0 && percent <= 30)
                                {
                                    <td style="color:red;font-weight:bold">@percent</td>
                                }
                                else if (percent >= 31 && percent <= 70)
                                {
                                    <td style="color:orange;font-weight:bold">@percent</td>
                                }
                                else if (percent >= 71 && percent <= 100)
                                {
                                    <td style="color:green;font-weight:bold">@percent</td>
                                }
                                else
                                {
                                    <td>@percent</td>
                                }
                            }
                        </tr>

                    }
                }
            </tbody>
        </table>
    }

</center>

Views/Home/Statistics.cshtml
@model List<Result>?

<div class="sidenav">
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Инфо/Связь" asp-action="InfoNContact" asp-controller="Home" />
    </form>
    <form method="get">
        <input type="submit" class="sidebutton" style="margin:5px 5px 5px 10px" value="Предложения" asp-controller="Offers" asp-action="Index" />
    </form>
</div>

<center>

@{
    <h1>Все ответы пользователей:</h1> <br /> <br />

    if (Model.Count == 0)
    {
            <h2>Ответов пользователей пока нет</h2>
    }
    else
    {   
        <div>
            <label class="sidebutton" style="font-weight:bold;width:283px;height:40pt;text-align:center;font-size:19pt">Верных ответов: @AverageMetrics.AverageCorrectAnswers</label>
            <label class="sidebutton" style="font-weight:bold;width:283px;height:40pt;text-align:center;font-size:19pt">Время ответа: @AverageMetrics.AverageTime</label>
            <label class="sidebutton" style="font-weight:bold;width:283px;height:40pt;text-align:center;font-size:19pt">Очков на ответ: @AverageMetrics.AveragePoints</label> <br />
        </div> <br />

        <form method="post">
            <div style="font-size:18pt">

                <input type="text" style="border-radius:5px;width:642px;font-weight:bold" placeholder="Поиск" name="searchString" />
                <input type="submit" style="background-color:green;color:white;border-radius:5px;width:214px;font-weight:bold" value="Найти" /> <br />

                <select class="sortselect" name="firstSortParameter" style="margin:20px 0 20px 0">
                    <option value="points">Количество очков</option>
                    <option value="correctAnswers">Верные ответы</option>
                    <option value="user">Имя пользователя</option>
                    <option value="time">Время</option>
                </select>


                <select class="sortselect" name="secondSortParameter" style="margin:20px 0 20px 6px">
                    <option value="none">Без второго параметра</option>
                    <option value="points">Количество очков</option>
                    <option value="time">Время</option>
                    <option value="user">Имя пользователя</option>
                    <option value="correctAnswers">Верные ответы</option>
                </select> <br/>
            </div>
        </form>
        <br />

        <table>
            <thead>
                <tr>
                    <th>Пользователь</th>
                    <th>Дано верных ответов</th>
                    <th>Очков</th>
                    <th>Время</th>
                </tr>
            </thead>
            <tbody>
                @{
                foreach (var result in Model)
                {
                    <tr>
                        <td>@result.UserName</td>
                        <td>@result.CorrectAnswers</td>
                        <td>@result.Points</td>
                        <td>@result.Time</td>
                    </tr>
                }
                }
            </tbody>
        </table>
    }
}

</center>